[build]
  command = "npm ci --legacy-peer-deps && npm run build:prod"
  publish = "dist/the-luxar/browser"

[context.production]
  command = "npm run build:prod"

[context.deploy-preview]
  command = "npm run build:prod"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
